### ISSUE TITLE
how do you make a git repo that only contains this files

### ISSUE THREAD

**Issue by mobop** [makccr/dot#1]
how do you use git for uploading  config files

**Comment by makccr** [comment]
I just create a separate folder, and then use symbolic links to put the dot files where they belong.

In practice it would look something like this: 
ln -s ~/Repo/dot/.config/ ~/.config
ln -s ~/Repo/dot/.tmux.conf ~/.tmux.conf
ln -s ~/Repo/dot/.bashrc ~/.bashrc
ln -s ~/Repo/dot/.profile ~/.profile
ln -s ~/Repo/dot/.bin/ ~/.bin
ln -s ~/Repo/dot/.gitconfig ~/.gitconfig 

Also here's a video I did that's tangentially related a while back:
https://youtu.be/pMTo95ZxnY4?list=PLIYVhRocqRoQ5Co9nakyZSmwM-p5sTLYf

**Comment by makccr** [comment]
I'm just going to leave the issue open, in case anyone else has the same question.
