### ISSUE TITLE
Incorrect vifm link in README

### ISSUE THREAD

**Issue by koolskateguy89** [makccr/dot#4]
The current vifm link in the README points to [The Victorian Institute of Forensic Medicine](https://www.vifm.org/), but I _think_ it’s meant to point to the [Vifm file manager](https://vifm.info/)

**Comment by koolskateguy89** [comment]
There’s already a [pull request](https://github.com/makccr/dot/pull/3) which solves this issue.

**Comment by makccr** [comment]
Thanks for that. I accepted the pull request, and I'll go ahead and close the issue.
