### ISSUE TITLE
Handling workspaces in awesome-wm without "Tag Switcher"

### ISSUE THREAD

**Issue by Jayaswal-Ayush** [makccr/dot#6]
## Use of [module/ewmh] for tags
polybar has a plugin for tags (workspaces too)  in awesome-wm and several other wms,
it will be better and cleaner to use ewmh plugin for the purpose and is almost as functional as i3 & bspwm modules.
```
[module/ewmh]
type = internal/xworkspaces
label-active = "  "
label-active-foreground = ${colors.foreground}
label-active-background = ${colors.background}
label-active-underline = ${colors.primary}
label-occupied = "  "
label-urgent = " 𥉉 "
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.background}
label-urgent-underline  = ${colors.alert}
label-empty ="  " 
label-empty-foreground = ${colors.background-alt}
```

**Comment by makccr** [comment]
Yes, but unfortunately this module doesn't really work at all with multi-head set-ups. I retry ever few months because I don't really like my hacky workaround, but as of now this module still isn't a good solution for my set-up.
