### ISSUE TITLE
Adding quotes via the script

### ISSUE THREAD

**Issue by andrewCohn** [makccr/dot#9]
This isn't an issue, necessarily, but I've been using your fortune setup to get quotes at the top of my terminal (and I love it!), but when I tried to manually add new quotes, I couldn't seem to get it working. How do you add new quotes?

**Comment by makccr** [comment]
You have to add them to the quotes file in scirpts/quotes then run a comman called 'strfile' which will replace the quotes.dat file based on what is in the quotes file
